### PR TITLE
Add SwiftLint

### PR DESCRIPTION
**Pull request by ruslankmlv**

### CODE REVIEW

**Comment by ruslankmlv** [comment]
In progress

**Comment by ruslankmlv** [comment]
@salutis We have file length violation in `SwitchControlTests`. Should we extract small test classes from it, like `SwitchControlLabelsTests`, `SwitchControlStackViewTests`, `SwitchControlTouchInteractionTests` etc. or is there a better way?

**Comment by rudolf-adamkovic** [comment]
@ruslankmlv 

> Should we extract small test classes from it [...] or is there a better way?

Good question. What about using extensions instead?
- `SwitchControlTests+StackView`
- `SwitchControlTests+Labels`
- ...

**Comment by ruslankmlv** [comment]
@salutis 

> What about using extensions instead?

Yes, sounds better, thanks

**Comment by ruslankmlv** [comment]
@salutis Please review when you get a chance.

**Review by rudolf-adamkovic — APPROVED** [review]
Great job!

**Comment by ruslankmlv** [comment]
@salutis Thank you for review

**Pull request merged**
