### PR TITLE
Make Xcode scheme shared for CI

### PR DESCRIPTION
**Pull request by rudolf-adamkovic**

### CODE REVIEW

**Comment by rudolf-adamkovic** [comment]
Hoped this would make CI (BuddyBuild) happy. Not the case. Closing.

**Comment by ruslankmlv** [comment]
@salutis I think we still need this for Carthage, here is what I get when I try to run `carthage update`:

```
*** Skipped building apple-switch-control due to the error:
Dependency "apple-switch-control" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at Optional("https://github.com/enfluid/apple-switch-control/issues/new")
```

Should we just use this PR or create a new branch and open a new PR?

**Comment by rudolf-adamkovic** [comment]
@ruslankmlv 

> Should we just use this PR or create a new branch and open a new PR?

Reopened. Please review.

**Review by ruslankmlv — APPROVED** [review]
LGTM

**Pull request merged**
