### PR TITLE
Set background color for unselected SwitchControlLabel

### PR DESCRIPTION
**Pull request by ruslankmlv**

### CODE REVIEW

**Comment by ruslankmlv** [comment]
@salutis Please review.

**Comment by rudolf-adamkovic** [comment]
@ruslankmlv Why `.white` instead of `nil`?

**Comment by rudolf-adamkovic** [comment]
@ruslankmlv Ah, I see. It's explained in #25. Will comment there.

**Comment by ruslankmlv** [comment]
@salutis Updated with a clear color. Please take a look.

**Review by rudolf-adamkovic — APPROVED** [review]

**Comment by ruslankmlv** [comment]
@salutis Thank you for review

**Pull request merged**
